---
title: "Results of Replications of Loftus & Palmer (1974, Study 2)"
author: "Many Legal Labs"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
knit: (function(inputFile, encoding) {
    rmarkdown::render(inputFile, encoding = encoding, output_dir = "./reports/")
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Run all necessary scripts

source("./scripts/simulate/loftus_simulation.R") # REPLACE WITH DATA IMPORTATION
source("./scripts/wrangle/loftus_prelim.R")
source("./scripts/calculate/loftus_core.R")
source("./scripts/analyze/loftus_analysis.R")

```

# Overview

# Hypothesis 1

## Meta-analysis of Replications

```{r}
loftus_h1_meta
```

## Forest Plot

```{r}
loftus_h1_forest
```

# Hypothesis 2

## Meta-analysis of Replications

```{r}
loftus_h2_meta
```

## Forest Plot

```{r}
loftus_h2_forest
```

# Hypothesis 3

## Meta-analysis of Replications

```{r}
loftus_h3_meta
```

## Forest Plot

```{r}
loftus_h3_forest
```

